### ISSUE TITLE
Infinite loop at 34%

### ISSUE THREAD

**Issue by Dzonny** [manticorp/CSVDump#12] opened 2016-05-06 22:09 UTC
Hello there,

I just tried this script, but when I try provided test csv files, but whatever I try i get "34% complete" message, and the 0 % right after that, looping those two in infinite loop, and "Remaining time: Infinity seconds" message at the bottom of the page.

Any suggestions?

**Comment by manticorp** [comment] 2016-05-07 11:58
Hello Dzonny,

I am unable to reproduce this error - could you provide me with a bit more information?
- What do you see in the javascript console when this happens?
- Which file are you trying to dump?

Thanks

**Comment by Dzonny** [comment] 2016-05-07 22:36
Hello there and thanks for your quick answer. 

You can see the script here:
http://abrasevic-valjevo.org/projekat/test/CSVDump/
You can use database: abrasevi_projekat and table: testiram
whatever csv I try to use I'm getting infinite loop, unless I'm missing something. 

Thanks.

**Comment by manticorp** [comment] 2016-05-08 08:14
Interesting - I was getting the following error:

Fatal error: Call to undefined method mysqli_result::fetch_all()

which means your server didn't have mysqlnd installed - I've updated the code so it no longer needs fetch_all, can you try pulling the latest commit and retrying?

Thanks

**Comment by Dzonny** [comment] 2016-05-08 18:27
Thanks once again!

I just tried with a new codes, now I'm getting this error:
Code     : 8  
File     : /home/abrasevi/public_html/projekat/test/CSVDump/CSVRunner/CSVRunner.php
Line     : 250
Message  : Undefined variable: rows

(You can still test it on a page i provided above)

**Comment by manticorp** [comment] 2016-05-08 18:43
Hmm...interesting, the error I'm getting is:

 LOAD DATA LOCAL INFILE '/home/abrasevi/public_html/projekat/test/CSVDump/var/output-566917994000.csv'
    INTO TABLE `longTest`
    FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\'
    LINES TERMINATED BY '\n'
(`Some Small Numbers`, `Some Big Numbers`, `Some Huge Numbers`, `Some Floats`, `Some Text`, `Some Dates`, `Some Long Text`)
There was an error running the query [The used command is not allowed with this MySQL version]

It looks like with a lot of the commands I've used, you really need the mysql native driver...see:

http://stackoverflow.com/questions/10762239/mysql-enable-load-data-local-infile

It might take me a while to rewrite this - I'll leave this issue open and work on it during the week.

**Comment by Dzonny** [comment] 2016-05-08 18:50
Thanks again!

On the other side: I tried the same script on another server I'm using, and it works like a charm, without problems! So, the problem on the server I linked to here is with the php version, settings or something.

Anyway, additional question, not quite related to the topic: I notice when I'm trying to add CSV file that has utf8 characters like for example "Ž" that content after that character is cut-off. 
For example I have a sentence "Autor se slaže sa navedenim u tekstu" and when I use this script this is what i have in database: "Autor se sla"
Is there a way to use utf8 characters here as well?

Thanks again, great script!

**Comment by manticorp** [comment] 2016-05-08 20:20
Okay - so this is probably down to the default table encoding in mysql on your mysql version.

I've updated the code to create UTF8 tables/columns by default now, as I think the use case for this tool suits it - however, this behaviour might change in the future, so I suggest writing a DB processor with a preImport method if you _need_ UTF8 columns.

I've updated the code to make this easier for people :)

An example would be:

```
<?php
include "Abstract.php";

/**
 * Processor_DB_Test
 */
class Processor_DB_Test extends Processor_DB_Abstract
{
    public function preImport(){
        // Change the column collation
        $this->modifyColumn('MyUTF8Column', Processor_DB_Abstract::TYPE_VARCHAR, 255, ['collate' => 'utf8_general_ci'], 'My utf8 column');
        // or
        $this->changeColumnCollation('MyOtherUTF8Column', 'utf8_general_ci', 'utf8');
        // or
        $columns = $this->getColumns();
        foreach($columns as $columnName => $columnDefinition) {
            $this->changeColumnCollation($columnName, 'utf8_general_ci');
        }

        return $this;
    }
}
```

**Comment by Dzonny** [comment] 2016-05-08 21:51
I just tried but I got the same results - although the table collation is "utf8_general_ci".
You can try the attached file that I'm trying to add as well, it has serbian utf8 characters (ž, č, ć, š).
So, what I noticed is that all characters after and including "ž" is not added to database, and for example "č" is displayed as "?".
[common.zip](https://github.com/manticorp/CSVDump/files/254125/common.zip)

**Comment by manticorp** [comment] 2016-05-08 22:44
Hmm...strange - when I try it, I get exactly the same result as what I see when I open the file as UTF8.

However, it would seem the file isn't UTF8 encoded? I'm not sure what it's supposed to say (sorry!) but when I open it as Windows 1252 or ISO 8859-1, I get a lot less question marks in the text, and a lot more of the characters you list - although there's still some question marks.

PHP seems to not be able to detect the charset, from what I can tell.

It may be worth trying to export/convert your file to UTF8 beforehand, or finding out what the encoding actually is beforehand, and explicitly setting the column character sets to that encoding (though I would recommend the former!)

Just out of interest, what software was used to save the CSV file?

--edit

As an example, when I just read the file in PHP and echo the contents, I get a lot of encoding point failures - it would seem PHP isn't able to read the character encoding of that file at all.

```
Autor se sla�e sa navedenim u tekstu
```

Thanks

**Comment by Dzonny** [comment] 2016-05-08 23:44
You're right, it's pretty odd that Excel (that's the answer to your latest questions) doesn't have an option to export with utf8 encoding, so I had to upload xls file to google docs, and export it from there in CSV format, which was with utf8 encoding.
When I use that in your tool, it works nicely!

Thanks once again, great work!

**Comment by manticorp** [comment] 2016-05-09 07:29
Haha yeah...Excel and office in general is pretty bad at handling encodings....and CSVs.... ¬_¬

http://stackoverflow.com/questions/4221176/excel-to-csv-with-utf8-encoding

Glad that you've managed to get it to work now though! I'll add a few lines to the README about encoding issues.

Regarding the need for mysqlnd drivers and enabling local file loading (for LOAD DATA LOCAL INFILE) - I think this is something I won't be changing. The LOAD DATA LOCAL INFILE is part of what makes it so speedy, and the program is completely insecure by it's very nature, so it shouldn't be used on production servers where this would be a problem.

see: http://dev.mysql.com/doc/refman/5.7/en/load-data-local.html

I may in future add an alternative method, but for now, it's sticking.

If it's all working okay for you now, can I close this?

Thanks

**Comment by Dzonny** [comment] 2016-05-10 22:37
Sure, no problems, I just closed this. Thanks once again for your answers, help and a nice script! :)

**Closed as completed** 2016-05-10 22:37 UTC
